-- Auto-generated by scripts/generate-store-monthly-seed.mjs
-- Source: scripts/data/monthly-report-store-september.csv
-- Run in Supabase SQL Editor AFTER 029_store_inventory.sql
--
-- Edit ONLY the uuid in DECLARE below: put your organizations.id between the quotes (valid UUID format).
-- Example: org_id uuid := 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'::uuid;
DO $$
DECLARE
  org_id uuid := '00000000-0000-0000-0000-000000000001'::uuid;
BEGIN

  INSERT INTO public.store_categories (organization_id, name, slug, sort_order)
  SELECT org_id, v.name, v.slug, v.ord
  FROM (
    VALUES
      ('General Store', 'general-store', 10),
      ('Housekeeping', 'housekeeping', 20),
      ('Laundry', 'laundry', 25),
      ('Staff Meal (Food)', 'staff-meal', 30),
      ('Stationeries', 'stationeries', 40),
      ('Kitchen consumable', 'kitchen-consumable', 50),
      ('Restaurant', 'restaurant', 60),
      ('Main Bar — Wine', 'main-bar-wine', 70),
      ('Main Bar — Beers & Soft Drinks', 'main-bar-beers-soft', 80),
      ('Beverages Store', 'beverages-store', 90),
      ('F & B inventory (crockery)', 'fb-inventory', 100)
  ) AS v(name, slug, ord)
  ON CONFLICT (organization_id, slug) DO NOTHING;

  -- Store opening stock items are seeded from:
  --   scripts/030_store_monthly_report_items_seed.sql
END $$;

